apiVersion: v1
kind: Service
metadata:
  name: {{ include "tigerbeetle.fullname" . }}
  labels:
    {{- include "tigerbeetle.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None # Headless service for StatefulSet
  ports:
    - name: tigerbeetle
      port: {{ .Values.service.port }}
      targetPort: tigerbeetle
      protocol: TCP
  selector:
    {{- include "tigerbeetle.selectorLabels" . | nindent 4 }}
