{{- if and .Values.railApi.enabled .Values.railApi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "iof.fullname" . }}-rail-api
  labels:
    {{- include "iof.componentLabels" (dict "component" "rail-api" "root" .) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "iof.fullname" . }}-rail-api
  minReplicas: {{ .Values.railApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.railApi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.railApi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.railApi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.railApi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.railApi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
